version: '2.4'

services:
  web:
    build: .
    container_name: sirius-backend
    mem_limit: 1g
    restart: unless-stopped
    ports:
      - "8000:8000"

  redis:
    image: redis
    container_name: redis
    mem_limit: 200m
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery-backend
    mem_limit: 200m
    command: celery -A sirius.configs worker -l info