version: '2.4'

services:
  web:
    build: .
    container_name: skypicker
    mem_limit: 500m
    restart: unless-stopped
    ports:
      - "8000:8000"

  redis:
    image: redis
    container_name: redis
    mem_limit: 200m
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery
    mem_limit: 200m
    command: celery -A skypicker worker -l info -B --scheduler django_celery_beat.schedulers:DatabaseScheduler