# Generated by Django 3.1.1 on 2020-09-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Авиалиния',
                'verbose_name_plural': 'Авиалинии',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='ID внешнего сервиса')),
                ('departure_time', models.PositiveBigIntegerField(db_index=True, verbose_name='Время вылета')),
                ('arrival_time', models.PositiveBigIntegerField(db_index=True, verbose_name='Время прибытия')),
                ('duration', models.PositiveIntegerField(verbose_name='Время в полете')),
                ('city_from', models.CharField(max_length=1000, verbose_name='Город вылета')),
                ('city_code_from', models.CharField(db_index=True, max_length=20, verbose_name='Город вылета (кодовое обозначение)')),
                ('city_to', models.CharField(max_length=1000, verbose_name='Город прибытия')),
                ('city_code_to', models.CharField(db_index=True, max_length=20, verbose_name='Город прибытия (кодовое обозначение)')),
                ('price', models.PositiveIntegerField(db_index=True, verbose_name='Цена')),
                ('currency', models.CharField(default='EUR', max_length=10, verbose_name='Валюта')),
                ('booking_token', models.CharField(max_length=2000, verbose_name='Токен для бронирования')),
                ('airlines', models.ManyToManyField(related_name='flights', to='app.Airline', verbose_name='Авиалинии')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
    ]
